version: '3.4'

services:
  highscore-exercise:
    image: ${DOCKER_REGISTRY-}highscoreexercise
    build:
      context: .
      dockerfile: highscore-exercise/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433
  game:
    build:
      context: ../ts-space-shooter-starter-09-points
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db

